spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: Fg3oK6bo0oDxuuBIDzFJ
            client-secret: I9MXAbwUUJ
            redirect-uri: http://localhost:4040/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - email
              - nickname
          kakao:
            client-name: kakao
            client-id: ac2c64c98329c7836b1366000db4ec39
            client-secret: 9AiVLThEKXlp7tUr995KNXVTx4vF4Ixh
            redirect-uri: http://localhost:4040/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - profile_nickname
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
